################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../opencv/lapack/dasum.c \
../opencv/lapack/daxpy.c \
../opencv/lapack/dbdsdc.c \
../opencv/lapack/dbdsqr.c \
../opencv/lapack/dcopy.c \
../opencv/lapack/ddot.c \
../opencv/lapack/dgebd2.c \
../opencv/lapack/dgebrd.c \
../opencv/lapack/dgelq2.c \
../opencv/lapack/dgelqf.c \
../opencv/lapack/dgels.c \
../opencv/lapack/dgelsd.c \
../opencv/lapack/dgemm.c \
../opencv/lapack/dgemv.c \
../opencv/lapack/dgeqr2.c \
../opencv/lapack/dgeqrf.c \
../opencv/lapack/dger.c \
../opencv/lapack/dgesdd.c \
../opencv/lapack/dgesv.c \
../opencv/lapack/dgetf2.c \
../opencv/lapack/dgetrf.c \
../opencv/lapack/dgetri.c \
../opencv/lapack/dgetrs.c \
../opencv/lapack/dlabad.c \
../opencv/lapack/dlabrd.c \
../opencv/lapack/dlacpy.c \
../opencv/lapack/dlae2.c \
../opencv/lapack/dlaebz.c \
../opencv/lapack/dlaed0.c \
../opencv/lapack/dlaed1.c \
../opencv/lapack/dlaed2.c \
../opencv/lapack/dlaed3.c \
../opencv/lapack/dlaed4.c \
../opencv/lapack/dlaed5.c \
../opencv/lapack/dlaed6.c \
../opencv/lapack/dlaed7.c \
../opencv/lapack/dlaed8.c \
../opencv/lapack/dlaed9.c \
../opencv/lapack/dlaeda.c \
../opencv/lapack/dlaev2.c \
../opencv/lapack/dlagtf.c \
../opencv/lapack/dlagts.c \
../opencv/lapack/dlaisnan.c \
../opencv/lapack/dlals0.c \
../opencv/lapack/dlalsa.c \
../opencv/lapack/dlalsd.c \
../opencv/lapack/dlamch.c \
../opencv/lapack/dlamrg.c \
../opencv/lapack/dlaneg.c \
../opencv/lapack/dlange.c \
../opencv/lapack/dlanst.c \
../opencv/lapack/dlansy.c \
../opencv/lapack/dlapy2.c \
../opencv/lapack/dlar1v.c \
../opencv/lapack/dlarf.c \
../opencv/lapack/dlarfb.c \
../opencv/lapack/dlarfg.c \
../opencv/lapack/dlarft.c \
../opencv/lapack/dlarnv.c \
../opencv/lapack/dlarra.c \
../opencv/lapack/dlarrb.c \
../opencv/lapack/dlarrc.c \
../opencv/lapack/dlarrd.c \
../opencv/lapack/dlarre.c \
../opencv/lapack/dlarrf.c \
../opencv/lapack/dlarrj.c \
../opencv/lapack/dlarrk.c \
../opencv/lapack/dlarrr.c \
../opencv/lapack/dlarrv.c \
../opencv/lapack/dlartg.c \
../opencv/lapack/dlaruv.c \
../opencv/lapack/dlas2.c \
../opencv/lapack/dlascl.c \
../opencv/lapack/dlasd0.c \
../opencv/lapack/dlasd1.c \
../opencv/lapack/dlasd2.c \
../opencv/lapack/dlasd3.c \
../opencv/lapack/dlasd4.c \
../opencv/lapack/dlasd5.c \
../opencv/lapack/dlasd6.c \
../opencv/lapack/dlasd7.c \
../opencv/lapack/dlasd8.c \
../opencv/lapack/dlasda.c \
../opencv/lapack/dlasdq.c \
../opencv/lapack/dlasdt.c \
../opencv/lapack/dlaset.c \
../opencv/lapack/dlasq1.c \
../opencv/lapack/dlasq2.c \
../opencv/lapack/dlasq3.c \
../opencv/lapack/dlasq4.c \
../opencv/lapack/dlasq5.c \
../opencv/lapack/dlasq6.c \
../opencv/lapack/dlasr.c \
../opencv/lapack/dlasrt.c \
../opencv/lapack/dlassq.c \
../opencv/lapack/dlasv2.c \
../opencv/lapack/dlaswp.c \
../opencv/lapack/dlasyf.c \
../opencv/lapack/dlatrd.c \
../opencv/lapack/dlauu2.c \
../opencv/lapack/dlauum.c \
../opencv/lapack/dlazq3.c \
../opencv/lapack/dlazq4.c \
../opencv/lapack/dnrm2.c \
../opencv/lapack/dorg2r.c \
../opencv/lapack/dorgbr.c \
../opencv/lapack/dorgl2.c \
../opencv/lapack/dorglq.c \
../opencv/lapack/dorgqr.c \
../opencv/lapack/dorm2l.c \
../opencv/lapack/dorm2r.c \
../opencv/lapack/dormbr.c \
../opencv/lapack/dorml2.c \
../opencv/lapack/dormlq.c \
../opencv/lapack/dormql.c \
../opencv/lapack/dormqr.c \
../opencv/lapack/dormtr.c \
../opencv/lapack/dpotf2.c \
../opencv/lapack/dpotrf.c \
../opencv/lapack/dpotri.c \
../opencv/lapack/dpotrs.c \
../opencv/lapack/drot.c \
../opencv/lapack/dscal.c \
../opencv/lapack/dstebz.c \
../opencv/lapack/dstein.c \
../opencv/lapack/dstemr.c \
../opencv/lapack/dsteqr.c \
../opencv/lapack/dsterf.c \
../opencv/lapack/dswap.c \
../opencv/lapack/dsyevr.c \
../opencv/lapack/dsymv.c \
../opencv/lapack/dsyr.c \
../opencv/lapack/dsyr2.c \
../opencv/lapack/dsyr2k.c \
../opencv/lapack/dsyrk.c \
../opencv/lapack/dsytd2.c \
../opencv/lapack/dsytf2.c \
../opencv/lapack/dsytrd.c \
../opencv/lapack/dsytrf.c \
../opencv/lapack/dsytri.c \
../opencv/lapack/dsytrs.c \
../opencv/lapack/dtrmm.c \
../opencv/lapack/dtrmv.c \
../opencv/lapack/dtrsm.c \
../opencv/lapack/dtrti2.c \
../opencv/lapack/dtrtri.c \
../opencv/lapack/dtrtrs.c \
../opencv/lapack/f77_aloc.c \
../opencv/lapack/idamax.c \
../opencv/lapack/ieeeck.c \
../opencv/lapack/ilaenv.c \
../opencv/lapack/iparmq.c \
../opencv/lapack/isamax.c \
../opencv/lapack/pow_di.c \
../opencv/lapack/pow_ii.c \
../opencv/lapack/pow_ri.c \
../opencv/lapack/precomp.c \
../opencv/lapack/s_cat.c \
../opencv/lapack/s_cmp.c \
../opencv/lapack/s_copy.c \
../opencv/lapack/sasum.c \
../opencv/lapack/saxpy.c \
../opencv/lapack/sbdsdc.c \
../opencv/lapack/sbdsqr.c \
../opencv/lapack/scopy.c \
../opencv/lapack/sdot.c \
../opencv/lapack/sgebd2.c \
../opencv/lapack/sgebrd.c \
../opencv/lapack/sgelq2.c \
../opencv/lapack/sgelqf.c \
../opencv/lapack/sgels.c \
../opencv/lapack/sgelsd.c \
../opencv/lapack/sgemm.c \
../opencv/lapack/sgemv.c \
../opencv/lapack/sgeqr2.c \
../opencv/lapack/sgeqrf.c \
../opencv/lapack/sger.c \
../opencv/lapack/sgesdd.c \
../opencv/lapack/sgesv.c \
../opencv/lapack/sgetf2.c \
../opencv/lapack/sgetrf.c \
../opencv/lapack/sgetri.c \
../opencv/lapack/sgetrs.c \
../opencv/lapack/slabad.c \
../opencv/lapack/slabrd.c \
../opencv/lapack/slacpy.c \
../opencv/lapack/slae2.c \
../opencv/lapack/slaebz.c \
../opencv/lapack/slaed0.c \
../opencv/lapack/slaed1.c \
../opencv/lapack/slaed2.c \
../opencv/lapack/slaed3.c \
../opencv/lapack/slaed4.c \
../opencv/lapack/slaed5.c \
../opencv/lapack/slaed6.c \
../opencv/lapack/slaed7.c \
../opencv/lapack/slaed8.c \
../opencv/lapack/slaed9.c \
../opencv/lapack/slaeda.c \
../opencv/lapack/slaev2.c \
../opencv/lapack/slagtf.c \
../opencv/lapack/slagts.c \
../opencv/lapack/slaisnan.c \
../opencv/lapack/slals0.c \
../opencv/lapack/slalsa.c \
../opencv/lapack/slalsd.c \
../opencv/lapack/slamch.c \
../opencv/lapack/slamrg.c \
../opencv/lapack/slaneg.c \
../opencv/lapack/slange.c \
../opencv/lapack/slanst.c \
../opencv/lapack/slansy.c \
../opencv/lapack/slapy2.c \
../opencv/lapack/slar1v.c \
../opencv/lapack/slarf.c \
../opencv/lapack/slarfb.c \
../opencv/lapack/slarfg.c \
../opencv/lapack/slarft.c \
../opencv/lapack/slarnv.c \
../opencv/lapack/slarra.c \
../opencv/lapack/slarrb.c \
../opencv/lapack/slarrc.c \
../opencv/lapack/slarrd.c \
../opencv/lapack/slarre.c \
../opencv/lapack/slarrf.c \
../opencv/lapack/slarrj.c \
../opencv/lapack/slarrk.c \
../opencv/lapack/slarrr.c \
../opencv/lapack/slarrv.c \
../opencv/lapack/slartg.c \
../opencv/lapack/slaruv.c \
../opencv/lapack/slas2.c \
../opencv/lapack/slascl.c \
../opencv/lapack/slasd0.c \
../opencv/lapack/slasd1.c \
../opencv/lapack/slasd2.c \
../opencv/lapack/slasd3.c \
../opencv/lapack/slasd4.c \
../opencv/lapack/slasd5.c \
../opencv/lapack/slasd6.c \
../opencv/lapack/slasd7.c \
../opencv/lapack/slasd8.c \
../opencv/lapack/slasda.c \
../opencv/lapack/slasdq.c \
../opencv/lapack/slasdt.c \
../opencv/lapack/slaset.c \
../opencv/lapack/slasq1.c \
../opencv/lapack/slasq2.c \
../opencv/lapack/slasq3.c \
../opencv/lapack/slasq4.c \
../opencv/lapack/slasq5.c \
../opencv/lapack/slasq6.c \
../opencv/lapack/slasr.c \
../opencv/lapack/slasrt.c \
../opencv/lapack/slassq.c \
../opencv/lapack/slasv2.c \
../opencv/lapack/slaswp.c \
../opencv/lapack/slatrd.c \
../opencv/lapack/slauu2.c \
../opencv/lapack/slauum.c \
../opencv/lapack/slazq3.c \
../opencv/lapack/slazq4.c \
../opencv/lapack/snrm2.c \
../opencv/lapack/sorg2r.c \
../opencv/lapack/sorgbr.c \
../opencv/lapack/sorgl2.c \
../opencv/lapack/sorglq.c \
../opencv/lapack/sorgqr.c \
../opencv/lapack/sorm2l.c \
../opencv/lapack/sorm2r.c \
../opencv/lapack/sormbr.c \
../opencv/lapack/sorml2.c \
../opencv/lapack/sormlq.c \
../opencv/lapack/sormql.c \
../opencv/lapack/sormqr.c \
../opencv/lapack/sormtr.c \
../opencv/lapack/spotf2.c \
../opencv/lapack/spotrf.c \
../opencv/lapack/spotri.c \
../opencv/lapack/spotrs.c \
../opencv/lapack/srot.c \
../opencv/lapack/sscal.c \
../opencv/lapack/sstebz.c \
../opencv/lapack/sstein.c \
../opencv/lapack/sstemr.c \
../opencv/lapack/ssteqr.c \
../opencv/lapack/ssterf.c \
../opencv/lapack/sswap.c \
../opencv/lapack/ssyevr.c \
../opencv/lapack/ssymv.c \
../opencv/lapack/ssyr2.c \
../opencv/lapack/ssyr2k.c \
../opencv/lapack/ssyrk.c \
../opencv/lapack/ssytd2.c \
../opencv/lapack/ssytrd.c \
../opencv/lapack/strmm.c \
../opencv/lapack/strmv.c \
../opencv/lapack/strsm.c \
../opencv/lapack/strti2.c \
../opencv/lapack/strtri.c \
../opencv/lapack/strtrs.c \
../opencv/lapack/xerbla.c 

OBJS += \
./opencv/lapack/dasum.o \
./opencv/lapack/daxpy.o \
./opencv/lapack/dbdsdc.o \
./opencv/lapack/dbdsqr.o \
./opencv/lapack/dcopy.o \
./opencv/lapack/ddot.o \
./opencv/lapack/dgebd2.o \
./opencv/lapack/dgebrd.o \
./opencv/lapack/dgelq2.o \
./opencv/lapack/dgelqf.o \
./opencv/lapack/dgels.o \
./opencv/lapack/dgelsd.o \
./opencv/lapack/dgemm.o \
./opencv/lapack/dgemv.o \
./opencv/lapack/dgeqr2.o \
./opencv/lapack/dgeqrf.o \
./opencv/lapack/dger.o \
./opencv/lapack/dgesdd.o \
./opencv/lapack/dgesv.o \
./opencv/lapack/dgetf2.o \
./opencv/lapack/dgetrf.o \
./opencv/lapack/dgetri.o \
./opencv/lapack/dgetrs.o \
./opencv/lapack/dlabad.o \
./opencv/lapack/dlabrd.o \
./opencv/lapack/dlacpy.o \
./opencv/lapack/dlae2.o \
./opencv/lapack/dlaebz.o \
./opencv/lapack/dlaed0.o \
./opencv/lapack/dlaed1.o \
./opencv/lapack/dlaed2.o \
./opencv/lapack/dlaed3.o \
./opencv/lapack/dlaed4.o \
./opencv/lapack/dlaed5.o \
./opencv/lapack/dlaed6.o \
./opencv/lapack/dlaed7.o \
./opencv/lapack/dlaed8.o \
./opencv/lapack/dlaed9.o \
./opencv/lapack/dlaeda.o \
./opencv/lapack/dlaev2.o \
./opencv/lapack/dlagtf.o \
./opencv/lapack/dlagts.o \
./opencv/lapack/dlaisnan.o \
./opencv/lapack/dlals0.o \
./opencv/lapack/dlalsa.o \
./opencv/lapack/dlalsd.o \
./opencv/lapack/dlamch.o \
./opencv/lapack/dlamrg.o \
./opencv/lapack/dlaneg.o \
./opencv/lapack/dlange.o \
./opencv/lapack/dlanst.o \
./opencv/lapack/dlansy.o \
./opencv/lapack/dlapy2.o \
./opencv/lapack/dlar1v.o \
./opencv/lapack/dlarf.o \
./opencv/lapack/dlarfb.o \
./opencv/lapack/dlarfg.o \
./opencv/lapack/dlarft.o \
./opencv/lapack/dlarnv.o \
./opencv/lapack/dlarra.o \
./opencv/lapack/dlarrb.o \
./opencv/lapack/dlarrc.o \
./opencv/lapack/dlarrd.o \
./opencv/lapack/dlarre.o \
./opencv/lapack/dlarrf.o \
./opencv/lapack/dlarrj.o \
./opencv/lapack/dlarrk.o \
./opencv/lapack/dlarrr.o \
./opencv/lapack/dlarrv.o \
./opencv/lapack/dlartg.o \
./opencv/lapack/dlaruv.o \
./opencv/lapack/dlas2.o \
./opencv/lapack/dlascl.o \
./opencv/lapack/dlasd0.o \
./opencv/lapack/dlasd1.o \
./opencv/lapack/dlasd2.o \
./opencv/lapack/dlasd3.o \
./opencv/lapack/dlasd4.o \
./opencv/lapack/dlasd5.o \
./opencv/lapack/dlasd6.o \
./opencv/lapack/dlasd7.o \
./opencv/lapack/dlasd8.o \
./opencv/lapack/dlasda.o \
./opencv/lapack/dlasdq.o \
./opencv/lapack/dlasdt.o \
./opencv/lapack/dlaset.o \
./opencv/lapack/dlasq1.o \
./opencv/lapack/dlasq2.o \
./opencv/lapack/dlasq3.o \
./opencv/lapack/dlasq4.o \
./opencv/lapack/dlasq5.o \
./opencv/lapack/dlasq6.o \
./opencv/lapack/dlasr.o \
./opencv/lapack/dlasrt.o \
./opencv/lapack/dlassq.o \
./opencv/lapack/dlasv2.o \
./opencv/lapack/dlaswp.o \
./opencv/lapack/dlasyf.o \
./opencv/lapack/dlatrd.o \
./opencv/lapack/dlauu2.o \
./opencv/lapack/dlauum.o \
./opencv/lapack/dlazq3.o \
./opencv/lapack/dlazq4.o \
./opencv/lapack/dnrm2.o \
./opencv/lapack/dorg2r.o \
./opencv/lapack/dorgbr.o \
./opencv/lapack/dorgl2.o \
./opencv/lapack/dorglq.o \
./opencv/lapack/dorgqr.o \
./opencv/lapack/dorm2l.o \
./opencv/lapack/dorm2r.o \
./opencv/lapack/dormbr.o \
./opencv/lapack/dorml2.o \
./opencv/lapack/dormlq.o \
./opencv/lapack/dormql.o \
./opencv/lapack/dormqr.o \
./opencv/lapack/dormtr.o \
./opencv/lapack/dpotf2.o \
./opencv/lapack/dpotrf.o \
./opencv/lapack/dpotri.o \
./opencv/lapack/dpotrs.o \
./opencv/lapack/drot.o \
./opencv/lapack/dscal.o \
./opencv/lapack/dstebz.o \
./opencv/lapack/dstein.o \
./opencv/lapack/dstemr.o \
./opencv/lapack/dsteqr.o \
./opencv/lapack/dsterf.o \
./opencv/lapack/dswap.o \
./opencv/lapack/dsyevr.o \
./opencv/lapack/dsymv.o \
./opencv/lapack/dsyr.o \
./opencv/lapack/dsyr2.o \
./opencv/lapack/dsyr2k.o \
./opencv/lapack/dsyrk.o \
./opencv/lapack/dsytd2.o \
./opencv/lapack/dsytf2.o \
./opencv/lapack/dsytrd.o \
./opencv/lapack/dsytrf.o \
./opencv/lapack/dsytri.o \
./opencv/lapack/dsytrs.o \
./opencv/lapack/dtrmm.o \
./opencv/lapack/dtrmv.o \
./opencv/lapack/dtrsm.o \
./opencv/lapack/dtrti2.o \
./opencv/lapack/dtrtri.o \
./opencv/lapack/dtrtrs.o \
./opencv/lapack/f77_aloc.o \
./opencv/lapack/idamax.o \
./opencv/lapack/ieeeck.o \
./opencv/lapack/ilaenv.o \
./opencv/lapack/iparmq.o \
./opencv/lapack/isamax.o \
./opencv/lapack/pow_di.o \
./opencv/lapack/pow_ii.o \
./opencv/lapack/pow_ri.o \
./opencv/lapack/precomp.o \
./opencv/lapack/s_cat.o \
./opencv/lapack/s_cmp.o \
./opencv/lapack/s_copy.o \
./opencv/lapack/sasum.o \
./opencv/lapack/saxpy.o \
./opencv/lapack/sbdsdc.o \
./opencv/lapack/sbdsqr.o \
./opencv/lapack/scopy.o \
./opencv/lapack/sdot.o \
./opencv/lapack/sgebd2.o \
./opencv/lapack/sgebrd.o \
./opencv/lapack/sgelq2.o \
./opencv/lapack/sgelqf.o \
./opencv/lapack/sgels.o \
./opencv/lapack/sgelsd.o \
./opencv/lapack/sgemm.o \
./opencv/lapack/sgemv.o \
./opencv/lapack/sgeqr2.o \
./opencv/lapack/sgeqrf.o \
./opencv/lapack/sger.o \
./opencv/lapack/sgesdd.o \
./opencv/lapack/sgesv.o \
./opencv/lapack/sgetf2.o \
./opencv/lapack/sgetrf.o \
./opencv/lapack/sgetri.o \
./opencv/lapack/sgetrs.o \
./opencv/lapack/slabad.o \
./opencv/lapack/slabrd.o \
./opencv/lapack/slacpy.o \
./opencv/lapack/slae2.o \
./opencv/lapack/slaebz.o \
./opencv/lapack/slaed0.o \
./opencv/lapack/slaed1.o \
./opencv/lapack/slaed2.o \
./opencv/lapack/slaed3.o \
./opencv/lapack/slaed4.o \
./opencv/lapack/slaed5.o \
./opencv/lapack/slaed6.o \
./opencv/lapack/slaed7.o \
./opencv/lapack/slaed8.o \
./opencv/lapack/slaed9.o \
./opencv/lapack/slaeda.o \
./opencv/lapack/slaev2.o \
./opencv/lapack/slagtf.o \
./opencv/lapack/slagts.o \
./opencv/lapack/slaisnan.o \
./opencv/lapack/slals0.o \
./opencv/lapack/slalsa.o \
./opencv/lapack/slalsd.o \
./opencv/lapack/slamch.o \
./opencv/lapack/slamrg.o \
./opencv/lapack/slaneg.o \
./opencv/lapack/slange.o \
./opencv/lapack/slanst.o \
./opencv/lapack/slansy.o \
./opencv/lapack/slapy2.o \
./opencv/lapack/slar1v.o \
./opencv/lapack/slarf.o \
./opencv/lapack/slarfb.o \
./opencv/lapack/slarfg.o \
./opencv/lapack/slarft.o \
./opencv/lapack/slarnv.o \
./opencv/lapack/slarra.o \
./opencv/lapack/slarrb.o \
./opencv/lapack/slarrc.o \
./opencv/lapack/slarrd.o \
./opencv/lapack/slarre.o \
./opencv/lapack/slarrf.o \
./opencv/lapack/slarrj.o \
./opencv/lapack/slarrk.o \
./opencv/lapack/slarrr.o \
./opencv/lapack/slarrv.o \
./opencv/lapack/slartg.o \
./opencv/lapack/slaruv.o \
./opencv/lapack/slas2.o \
./opencv/lapack/slascl.o \
./opencv/lapack/slasd0.o \
./opencv/lapack/slasd1.o \
./opencv/lapack/slasd2.o \
./opencv/lapack/slasd3.o \
./opencv/lapack/slasd4.o \
./opencv/lapack/slasd5.o \
./opencv/lapack/slasd6.o \
./opencv/lapack/slasd7.o \
./opencv/lapack/slasd8.o \
./opencv/lapack/slasda.o \
./opencv/lapack/slasdq.o \
./opencv/lapack/slasdt.o \
./opencv/lapack/slaset.o \
./opencv/lapack/slasq1.o \
./opencv/lapack/slasq2.o \
./opencv/lapack/slasq3.o \
./opencv/lapack/slasq4.o \
./opencv/lapack/slasq5.o \
./opencv/lapack/slasq6.o \
./opencv/lapack/slasr.o \
./opencv/lapack/slasrt.o \
./opencv/lapack/slassq.o \
./opencv/lapack/slasv2.o \
./opencv/lapack/slaswp.o \
./opencv/lapack/slatrd.o \
./opencv/lapack/slauu2.o \
./opencv/lapack/slauum.o \
./opencv/lapack/slazq3.o \
./opencv/lapack/slazq4.o \
./opencv/lapack/snrm2.o \
./opencv/lapack/sorg2r.o \
./opencv/lapack/sorgbr.o \
./opencv/lapack/sorgl2.o \
./opencv/lapack/sorglq.o \
./opencv/lapack/sorgqr.o \
./opencv/lapack/sorm2l.o \
./opencv/lapack/sorm2r.o \
./opencv/lapack/sormbr.o \
./opencv/lapack/sorml2.o \
./opencv/lapack/sormlq.o \
./opencv/lapack/sormql.o \
./opencv/lapack/sormqr.o \
./opencv/lapack/sormtr.o \
./opencv/lapack/spotf2.o \
./opencv/lapack/spotrf.o \
./opencv/lapack/spotri.o \
./opencv/lapack/spotrs.o \
./opencv/lapack/srot.o \
./opencv/lapack/sscal.o \
./opencv/lapack/sstebz.o \
./opencv/lapack/sstein.o \
./opencv/lapack/sstemr.o \
./opencv/lapack/ssteqr.o \
./opencv/lapack/ssterf.o \
./opencv/lapack/sswap.o \
./opencv/lapack/ssyevr.o \
./opencv/lapack/ssymv.o \
./opencv/lapack/ssyr2.o \
./opencv/lapack/ssyr2k.o \
./opencv/lapack/ssyrk.o \
./opencv/lapack/ssytd2.o \
./opencv/lapack/ssytrd.o \
./opencv/lapack/strmm.o \
./opencv/lapack/strmv.o \
./opencv/lapack/strsm.o \
./opencv/lapack/strti2.o \
./opencv/lapack/strtri.o \
./opencv/lapack/strtrs.o \
./opencv/lapack/xerbla.o 

C_DEPS += \
./opencv/lapack/dasum.d \
./opencv/lapack/daxpy.d \
./opencv/lapack/dbdsdc.d \
./opencv/lapack/dbdsqr.d \
./opencv/lapack/dcopy.d \
./opencv/lapack/ddot.d \
./opencv/lapack/dgebd2.d \
./opencv/lapack/dgebrd.d \
./opencv/lapack/dgelq2.d \
./opencv/lapack/dgelqf.d \
./opencv/lapack/dgels.d \
./opencv/lapack/dgelsd.d \
./opencv/lapack/dgemm.d \
./opencv/lapack/dgemv.d \
./opencv/lapack/dgeqr2.d \
./opencv/lapack/dgeqrf.d \
./opencv/lapack/dger.d \
./opencv/lapack/dgesdd.d \
./opencv/lapack/dgesv.d \
./opencv/lapack/dgetf2.d \
./opencv/lapack/dgetrf.d \
./opencv/lapack/dgetri.d \
./opencv/lapack/dgetrs.d \
./opencv/lapack/dlabad.d \
./opencv/lapack/dlabrd.d \
./opencv/lapack/dlacpy.d \
./opencv/lapack/dlae2.d \
./opencv/lapack/dlaebz.d \
./opencv/lapack/dlaed0.d \
./opencv/lapack/dlaed1.d \
./opencv/lapack/dlaed2.d \
./opencv/lapack/dlaed3.d \
./opencv/lapack/dlaed4.d \
./opencv/lapack/dlaed5.d \
./opencv/lapack/dlaed6.d \
./opencv/lapack/dlaed7.d \
./opencv/lapack/dlaed8.d \
./opencv/lapack/dlaed9.d \
./opencv/lapack/dlaeda.d \
./opencv/lapack/dlaev2.d \
./opencv/lapack/dlagtf.d \
./opencv/lapack/dlagts.d \
./opencv/lapack/dlaisnan.d \
./opencv/lapack/dlals0.d \
./opencv/lapack/dlalsa.d \
./opencv/lapack/dlalsd.d \
./opencv/lapack/dlamch.d \
./opencv/lapack/dlamrg.d \
./opencv/lapack/dlaneg.d \
./opencv/lapack/dlange.d \
./opencv/lapack/dlanst.d \
./opencv/lapack/dlansy.d \
./opencv/lapack/dlapy2.d \
./opencv/lapack/dlar1v.d \
./opencv/lapack/dlarf.d \
./opencv/lapack/dlarfb.d \
./opencv/lapack/dlarfg.d \
./opencv/lapack/dlarft.d \
./opencv/lapack/dlarnv.d \
./opencv/lapack/dlarra.d \
./opencv/lapack/dlarrb.d \
./opencv/lapack/dlarrc.d \
./opencv/lapack/dlarrd.d \
./opencv/lapack/dlarre.d \
./opencv/lapack/dlarrf.d \
./opencv/lapack/dlarrj.d \
./opencv/lapack/dlarrk.d \
./opencv/lapack/dlarrr.d \
./opencv/lapack/dlarrv.d \
./opencv/lapack/dlartg.d \
./opencv/lapack/dlaruv.d \
./opencv/lapack/dlas2.d \
./opencv/lapack/dlascl.d \
./opencv/lapack/dlasd0.d \
./opencv/lapack/dlasd1.d \
./opencv/lapack/dlasd2.d \
./opencv/lapack/dlasd3.d \
./opencv/lapack/dlasd4.d \
./opencv/lapack/dlasd5.d \
./opencv/lapack/dlasd6.d \
./opencv/lapack/dlasd7.d \
./opencv/lapack/dlasd8.d \
./opencv/lapack/dlasda.d \
./opencv/lapack/dlasdq.d \
./opencv/lapack/dlasdt.d \
./opencv/lapack/dlaset.d \
./opencv/lapack/dlasq1.d \
./opencv/lapack/dlasq2.d \
./opencv/lapack/dlasq3.d \
./opencv/lapack/dlasq4.d \
./opencv/lapack/dlasq5.d \
./opencv/lapack/dlasq6.d \
./opencv/lapack/dlasr.d \
./opencv/lapack/dlasrt.d \
./opencv/lapack/dlassq.d \
./opencv/lapack/dlasv2.d \
./opencv/lapack/dlaswp.d \
./opencv/lapack/dlasyf.d \
./opencv/lapack/dlatrd.d \
./opencv/lapack/dlauu2.d \
./opencv/lapack/dlauum.d \
./opencv/lapack/dlazq3.d \
./opencv/lapack/dlazq4.d \
./opencv/lapack/dnrm2.d \
./opencv/lapack/dorg2r.d \
./opencv/lapack/dorgbr.d \
./opencv/lapack/dorgl2.d \
./opencv/lapack/dorglq.d \
./opencv/lapack/dorgqr.d \
./opencv/lapack/dorm2l.d \
./opencv/lapack/dorm2r.d \
./opencv/lapack/dormbr.d \
./opencv/lapack/dorml2.d \
./opencv/lapack/dormlq.d \
./opencv/lapack/dormql.d \
./opencv/lapack/dormqr.d \
./opencv/lapack/dormtr.d \
./opencv/lapack/dpotf2.d \
./opencv/lapack/dpotrf.d \
./opencv/lapack/dpotri.d \
./opencv/lapack/dpotrs.d \
./opencv/lapack/drot.d \
./opencv/lapack/dscal.d \
./opencv/lapack/dstebz.d \
./opencv/lapack/dstein.d \
./opencv/lapack/dstemr.d \
./opencv/lapack/dsteqr.d \
./opencv/lapack/dsterf.d \
./opencv/lapack/dswap.d \
./opencv/lapack/dsyevr.d \
./opencv/lapack/dsymv.d \
./opencv/lapack/dsyr.d \
./opencv/lapack/dsyr2.d \
./opencv/lapack/dsyr2k.d \
./opencv/lapack/dsyrk.d \
./opencv/lapack/dsytd2.d \
./opencv/lapack/dsytf2.d \
./opencv/lapack/dsytrd.d \
./opencv/lapack/dsytrf.d \
./opencv/lapack/dsytri.d \
./opencv/lapack/dsytrs.d \
./opencv/lapack/dtrmm.d \
./opencv/lapack/dtrmv.d \
./opencv/lapack/dtrsm.d \
./opencv/lapack/dtrti2.d \
./opencv/lapack/dtrtri.d \
./opencv/lapack/dtrtrs.d \
./opencv/lapack/f77_aloc.d \
./opencv/lapack/idamax.d \
./opencv/lapack/ieeeck.d \
./opencv/lapack/ilaenv.d \
./opencv/lapack/iparmq.d \
./opencv/lapack/isamax.d \
./opencv/lapack/pow_di.d \
./opencv/lapack/pow_ii.d \
./opencv/lapack/pow_ri.d \
./opencv/lapack/precomp.d \
./opencv/lapack/s_cat.d \
./opencv/lapack/s_cmp.d \
./opencv/lapack/s_copy.d \
./opencv/lapack/sasum.d \
./opencv/lapack/saxpy.d \
./opencv/lapack/sbdsdc.d \
./opencv/lapack/sbdsqr.d \
./opencv/lapack/scopy.d \
./opencv/lapack/sdot.d \
./opencv/lapack/sgebd2.d \
./opencv/lapack/sgebrd.d \
./opencv/lapack/sgelq2.d \
./opencv/lapack/sgelqf.d \
./opencv/lapack/sgels.d \
./opencv/lapack/sgelsd.d \
./opencv/lapack/sgemm.d \
./opencv/lapack/sgemv.d \
./opencv/lapack/sgeqr2.d \
./opencv/lapack/sgeqrf.d \
./opencv/lapack/sger.d \
./opencv/lapack/sgesdd.d \
./opencv/lapack/sgesv.d \
./opencv/lapack/sgetf2.d \
./opencv/lapack/sgetrf.d \
./opencv/lapack/sgetri.d \
./opencv/lapack/sgetrs.d \
./opencv/lapack/slabad.d \
./opencv/lapack/slabrd.d \
./opencv/lapack/slacpy.d \
./opencv/lapack/slae2.d \
./opencv/lapack/slaebz.d \
./opencv/lapack/slaed0.d \
./opencv/lapack/slaed1.d \
./opencv/lapack/slaed2.d \
./opencv/lapack/slaed3.d \
./opencv/lapack/slaed4.d \
./opencv/lapack/slaed5.d \
./opencv/lapack/slaed6.d \
./opencv/lapack/slaed7.d \
./opencv/lapack/slaed8.d \
./opencv/lapack/slaed9.d \
./opencv/lapack/slaeda.d \
./opencv/lapack/slaev2.d \
./opencv/lapack/slagtf.d \
./opencv/lapack/slagts.d \
./opencv/lapack/slaisnan.d \
./opencv/lapack/slals0.d \
./opencv/lapack/slalsa.d \
./opencv/lapack/slalsd.d \
./opencv/lapack/slamch.d \
./opencv/lapack/slamrg.d \
./opencv/lapack/slaneg.d \
./opencv/lapack/slange.d \
./opencv/lapack/slanst.d \
./opencv/lapack/slansy.d \
./opencv/lapack/slapy2.d \
./opencv/lapack/slar1v.d \
./opencv/lapack/slarf.d \
./opencv/lapack/slarfb.d \
./opencv/lapack/slarfg.d \
./opencv/lapack/slarft.d \
./opencv/lapack/slarnv.d \
./opencv/lapack/slarra.d \
./opencv/lapack/slarrb.d \
./opencv/lapack/slarrc.d \
./opencv/lapack/slarrd.d \
./opencv/lapack/slarre.d \
./opencv/lapack/slarrf.d \
./opencv/lapack/slarrj.d \
./opencv/lapack/slarrk.d \
./opencv/lapack/slarrr.d \
./opencv/lapack/slarrv.d \
./opencv/lapack/slartg.d \
./opencv/lapack/slaruv.d \
./opencv/lapack/slas2.d \
./opencv/lapack/slascl.d \
./opencv/lapack/slasd0.d \
./opencv/lapack/slasd1.d \
./opencv/lapack/slasd2.d \
./opencv/lapack/slasd3.d \
./opencv/lapack/slasd4.d \
./opencv/lapack/slasd5.d \
./opencv/lapack/slasd6.d \
./opencv/lapack/slasd7.d \
./opencv/lapack/slasd8.d \
./opencv/lapack/slasda.d \
./opencv/lapack/slasdq.d \
./opencv/lapack/slasdt.d \
./opencv/lapack/slaset.d \
./opencv/lapack/slasq1.d \
./opencv/lapack/slasq2.d \
./opencv/lapack/slasq3.d \
./opencv/lapack/slasq4.d \
./opencv/lapack/slasq5.d \
./opencv/lapack/slasq6.d \
./opencv/lapack/slasr.d \
./opencv/lapack/slasrt.d \
./opencv/lapack/slassq.d \
./opencv/lapack/slasv2.d \
./opencv/lapack/slaswp.d \
./opencv/lapack/slatrd.d \
./opencv/lapack/slauu2.d \
./opencv/lapack/slauum.d \
./opencv/lapack/slazq3.d \
./opencv/lapack/slazq4.d \
./opencv/lapack/snrm2.d \
./opencv/lapack/sorg2r.d \
./opencv/lapack/sorgbr.d \
./opencv/lapack/sorgl2.d \
./opencv/lapack/sorglq.d \
./opencv/lapack/sorgqr.d \
./opencv/lapack/sorm2l.d \
./opencv/lapack/sorm2r.d \
./opencv/lapack/sormbr.d \
./opencv/lapack/sorml2.d \
./opencv/lapack/sormlq.d \
./opencv/lapack/sormql.d \
./opencv/lapack/sormqr.d \
./opencv/lapack/sormtr.d \
./opencv/lapack/spotf2.d \
./opencv/lapack/spotrf.d \
./opencv/lapack/spotri.d \
./opencv/lapack/spotrs.d \
./opencv/lapack/srot.d \
./opencv/lapack/sscal.d \
./opencv/lapack/sstebz.d \
./opencv/lapack/sstein.d \
./opencv/lapack/sstemr.d \
./opencv/lapack/ssteqr.d \
./opencv/lapack/ssterf.d \
./opencv/lapack/sswap.d \
./opencv/lapack/ssyevr.d \
./opencv/lapack/ssymv.d \
./opencv/lapack/ssyr2.d \
./opencv/lapack/ssyr2k.d \
./opencv/lapack/ssyrk.d \
./opencv/lapack/ssytd2.d \
./opencv/lapack/ssytrd.d \
./opencv/lapack/strmm.d \
./opencv/lapack/strmv.d \
./opencv/lapack/strsm.d \
./opencv/lapack/strti2.d \
./opencv/lapack/strtri.d \
./opencv/lapack/strtrs.d \
./opencv/lapack/xerbla.d 


# Each subdirectory must supply rules for building sources it contributes
opencv/lapack/%.o: ../opencv/lapack/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -m64 -fPIC -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


